// <auto-generated />
using System;
using Holmes.Services.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holmes.Services.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    [Migration("20251224021115_InitialServices")]
    partial class InitialServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceCatalogSnapshotDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_customer");

                    b.HasIndex("CustomerId", "Version")
                        .IsUnique()
                        .HasDatabaseName("idx_customer_version");

                    b.ToTable("service_catalog_snapshots", (string)null);
                });

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CanceledAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CatalogSnapshotId")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DispatchedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FailedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int?>("ScopeType")
                        .HasColumnType("int");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("VendorReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("idx_customer_status");

                    b.HasIndex("OrderId", "Tier")
                        .HasDatabaseName("idx_order_tier");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_status_created");

                    b.HasIndex("VendorCode", "VendorReferenceId")
                        .HasDatabaseName("idx_vendor_ref");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DispatchedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FailedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int?>("ResultStatus")
                        .HasColumnType("int");

                    b.Property<string>("ScopeType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("VendorReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_proj_order");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("idx_proj_customer_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_proj_status_created");

                    b.ToTable("service_projections", (string)null);
                });

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceResultDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime?>("NormalizedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawResponseHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordsJson")
                        .HasColumnType("json");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VendorReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("idx_service");

                    b.ToTable("service_results", (string)null);
                });

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceResultDb", b =>
                {
                    b.HasOne("Holmes.Services.Infrastructure.Sql.Entities.ServiceDb", "Service")
                        .WithOne("Result")
                        .HasForeignKey("Holmes.Services.Infrastructure.Sql.Entities.ServiceResultDb", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Holmes.Services.Infrastructure.Sql.Entities.ServiceDb", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
