// <auto-generated />
using System;
using Holmes.Notifications.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holmes.Notifications.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260105142231_InitialNotifications")]
    partial class InitialNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Holmes.Notifications.Infrastructure.Sql.Entities.DeliveryAttemptDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<TimeSpan?>("NextRetryAfter")
                        .HasColumnType("time(6)");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("NotificationId");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("Holmes.Notifications.Infrastructure.Sql.Entities.NotificationDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ContentTemplateDataJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("ContentTemplateId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAdverseAction")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RecipientDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RecipientMetadataJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Status", "ScheduledFor");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Holmes.Notifications.Infrastructure.Sql.Entities.NotificationProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BouncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAdverseAction")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("notification_projections", (string)null);
                });

            modelBuilder.Entity("Holmes.Notifications.Infrastructure.Sql.Entities.DeliveryAttemptDb", b =>
                {
                    b.HasOne("Holmes.Notifications.Infrastructure.Sql.Entities.NotificationDb", "Notification")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Holmes.Notifications.Infrastructure.Sql.Entities.NotificationDb", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
