// <auto-generated />
using System;
using Holmes.Subjects.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holmes.Subjects.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(SubjectsDbContext))]
    partial class SubjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectAliasDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "GivenName", "FamilyName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("subject_aliases", (string)null);
                });

            modelBuilder.Entity("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectDb", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MergedBy")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("MergedIntoSubjectId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("SubjectId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectDirectoryDb", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("AliasCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsMerged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("SubjectId");

                    b.ToTable("subject_directory", (string)null);
                });

            modelBuilder.Entity("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectAliasDb", b =>
                {
                    b.HasOne("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectDb", "Subject")
                        .WithMany("Aliases")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Holmes.Subjects.Infrastructure.Sql.Entities.SubjectDb", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
