// <auto-generated />
using System;
using Holmes.SlaClocks.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holmes.SlaClocks.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(SlaClockDbContext))]
    [Migration("20251212160603_InitialSlaClocks")]
    partial class InitialSlaClocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Holmes.SlaClocks.Infrastructure.Sql.Entities.HolidayDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsObserved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Date");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("Holmes.SlaClocks.Infrastructure.Sql.Entities.SlaClockDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<long>("AccumulatedPauseMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AtRiskAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AtRiskThresholdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AtRiskThresholdPercent")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("BreachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("DeadlineAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TargetBusinessDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("CustomerId", "State");

                    b.HasIndex("State", "AtRiskThresholdAt");

                    b.HasIndex("State", "DeadlineAt");

                    b.ToTable("sla_clocks", (string)null);
                });

            modelBuilder.Entity("Holmes.SlaClocks.Infrastructure.Sql.Entities.SlaClockProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<long>("AccumulatedPauseMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AtRiskAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AtRiskThresholdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AtRiskThresholdPercent")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("BreachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("DeadlineAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TargetBusinessDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("CustomerId", "State");

                    b.HasIndex("State", "AtRiskThresholdAt");

                    b.HasIndex("State", "DeadlineAt");

                    b.ToTable("sla_clock_projections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
